<div class="page-title" xmlns="http://www.w3.org/1999/html">
    <h2><?php echo $this->__('Оставте свой отзыв!') ?></h2>
</div>
<div id="comments"></div>
<div>
    <form action="index/createNewPost/" method="post" enctype="multipart/form-data">
        <div>
            <label for="name"><em></em><?php echo $this->__('Имя') ?></label>

            <div class="input-box">
                <input type="text" name="name" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="name"
                       class="input-text required-entry validate-email" title="<?php echo $this->__('Имя') ?>" "/>
            </div>
            <div class="input-box">
                <textarea placeholder="Отзыв" name="comment" " title="<?php echo $this->__('Отзыв') ?>"/ ></textarea>
            </div>

            <div class="col-2 registered-users">
                <button type="submit" class="button" title="<?php echo $this->__('Отправить') ?>" name="send"
                        id="send">
                    <span><span><?php echo $this->__('Отправить') ?></span></span></button>
            </div>

        </div>
    </form>
</div>
<!--<script type="text/javascript">-->
<!--    function loadXMLDoc()-->
<!--    {-->
<!--        var xmlhttp;-->
<!--        if (window.XMLHttpRequest)-->
<!--        {// code for IE7+, Firefox, Chrome, Opera, Safari-->
<!--            xmlhttp=new XMLHttpRequest();-->
<!--        }-->
<!---->
<!--        xmlhttp.onreadystatechange=function()-->
<!--        {-->
<!--            if (xmlhttp.readyState==4 && xmlhttp.status==200)-->
<!--            {-->
<!--                document.getElementById("myDiv").innerHTML=xmlhttp.responseText;-->
<!--            }-->
<!--        }-->
<!--        xmlhttp.open("GET","index/ajax",true);-->
<!--        xmlhttp.send();-->
<!--    }-->
<!--</script>-->
<!---->
<!--<div id="myDiv"><h2>Let AJAX change this text</h2></div>-->
<!--<button type="button" onclick="loadXMLDoc()">Change Content</button>-->
<!--<script>-->
<!--function showCustomer(str)-->
<!--{-->
<!--var xmlhttp;-->
<!--if (str=="")-->
<!--{-->
<!--document.getElementById("txtHint").innerHTML="";-->
<!--return;-->
<!--}-->
<!--if (window.XMLHttpRequest)-->
<!--{// code for IE7+, Firefox, Chrome, Opera, Safari-->
<!--xmlhttp=new XMLHttpRequest();-->
<!--}-->
<!---->
<!--if (xmlhttp.readyState==4 && xmlhttp.status==200)-->
<!--{-->
<!--document.getElementById("txtHint").innerHTML=xmlhttp.responseText;-->
<!--}-->
<!--}-->
<!--xmlhttp.open("GET","getcustomer.asp?q="+str,true);-->
<!--xmlhttp.send();-->
<!--}-->
<!--</script>-->
<!--</head>-->
<!--<body>-->
<!---->
<!--<form action="">-->
<!--<select name="customers" onchange="showCustomer(this.value)">-->
<!--<option value="">Select a customer:</option>-->
<!--<option value="ALFKI">Alfreds Futterkiste</option>-->
<!--<option value="NORTS ">North/South</option>-->
<!--<option value="WOLZA">Wolski Zajazd</option>-->
<!--</select>-->
<!--</form>-->
<!--<br>-->
<!--<div id="txtHint">Customer info will be listed here...</div>-->
