<div id="allComments"></div>
<div class="page-title" xmlns="http://www.w3.org/1999/html">
    <h2><?php echo $this->__('Оставте свой отзыв!') ?></h2>
</div>
<div>
    <form action="javascript:send();" method="post" enctype="multipart/form-data">
        <div>
            <label for="name"><em></em><?php echo $this->__('Имя') ?></label>

            <div class="input-box">
                <input type="text" name="name" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="name"
                       class="input-text required-entry validate-email" title="<?php echo $this->__('Имя') ?>" "/>
            </div>
            <div class="input-box">
                <textarea placeholder="Отзыв" name="comment" id="comment" " title="<?php echo $this->__('Отзыв') ?>"/
                ></textarea>
            </div>

            <div class="col-2 registered-users">
                <button type="submit" class="button" title="<?php echo $this->__('Отправить') ?>" name="send"
                        id="send">
                    <span><span><?php echo $this->__('Отправить') ?></span></span></button>
            </div>

        </div>
    </form>
</div>
<script type="text/javascript">
    function send() {
        jQuery('#send').click(function () {
                var name = jQuery("#name");
                var comment = jQuery("#comment");
                jQuery.ajax({
                    type: "POST",
                    url: 'index/createNewPost',
                    data: "name=" + name + "&comment=" + comment,
                    success: function (data) {
                        jQuery('#allComments').html(data);
                        jQuery("#name").val('')
                        jQuery("#comment").val('')
                    }
                });
            }
        )
        ;
    }
</script>
<!--<button type="button" id="try">BLABLABLA</button>-->
<!--<script type="text/javascript">-->
<!--    jQuery('#send').click(function () {-->
<!--        jQuery.ajax({-->
<!--            url: 'index/ajax',-->
<!--            dataType: "html",-->
<!--            success: function (data) {-->
<!--                jQuery('#allComments').html(data);-->
<!--            }-->
<!--        });-->
<!--    });-->
<!--</script>-->