<div class="page-title" xmlns="http://www.w3.org/1999/html">
    <h2><?php echo $this->__('Отзывы наших гостей:') ?></h2>
</div>
<!--<div>--><?php //$posts = Mage::getModel('guestbook/guestbookposts')->getCollection();
//            foreach($posts as $guestpost){
//                echo 'Id:'.$guestpost->getId() .'<br>';
//                echo 'Name: ' . $guestpost->getName() . '<br>';
//                echo 'Post: ' .nl2br($guestpost->getPost()) . '<hr>';
//            }
//    ?><!--</div>-->